# Generated by Django 5.0.1 on 2024-02-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_courseitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseItem',
        ),
    ]
