# Generated by Django 5.0.1 on 2024-02-08 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_dppcourse_dppquestion_dppscoreboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subsubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quiz_file_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='dppCourse',
        ),
        migrations.RemoveField(
            model_name='dppscoreboard',
            name='course',
        ),
        migrations.RemoveField(
            model_name='dppscoreboard',
            name='user',
        ),
        migrations.AddField(
            model_name='qquestion',
            name='subsubtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subsubtopic'),
        ),
        migrations.AddField(
            model_name='subsubtopic',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subtopic'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.topic'),
        ),
        migrations.DeleteModel(
            name='dppQuestion',
        ),
        migrations.DeleteModel(
            name='dppScoreBoard',
        ),
    ]
