# Generated by Django 5.0.1 on 2024-02-10 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_subsubtopic_subtopic_remove_subtopic_topic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionbankCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='qbankscoreboard',
            name='course',
        ),
        migrations.RemoveField(
            model_name='qbankscoreboard',
            name='user',
        ),
        migrations.CreateModel(
            name='QuestionbankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.IntegerField()),
                ('option_one', models.CharField(max_length=100)),
                ('option_two', models.CharField(max_length=100)),
                ('option_three', models.CharField(blank=True, max_length=100)),
                ('option_four', models.CharField(blank=True, max_length=100)),
                ('marks', models.IntegerField(default=1)),
                ('Questionbank_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questionbankcourse')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionbankScoreBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('Questionbankcourse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.questionbankcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='QbankQuestion',
        ),
        migrations.DeleteModel(
            name='QbankScoreBoard',
        ),
    ]
